include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Code Style
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - require_trailing_commas
    - avoid_print
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_relative_imports
    - sort_child_properties_last

    # Design System Enforcement
    - use_full_hex_values_for_flutter_colors  # Warn about hardcoded colors
    - avoid_web_libraries_in_flutter           # Prevent dart:html colors
