/**
 * Base Email Template - 2025 Modern Design
 *
 * Core template structure used by all email types.
 * Provides consistent layout, styling, and dark mode support.
 */

import {getBaseHtmlWrapper} from "../styles/base-styles";
import {getComponentStyles} from "../styles/components";
import {wrapEmailContent, generateFooter, FooterOptions} from "../utils/template-helpers";

/**
 * Base email template options
 */
export interface BaseEmailOptions {
  /** Header HTML (generated by generateHeader) */
  header: string;

  /** Main content HTML (cards, alerts, buttons, etc.) */
  content: string;

  /** Footer options (optional) */
  footer?: FooterOptions;
}

/**
 * Generate complete email HTML
 *
 * Takes header, content, and footer options and returns a complete
 * HTML email with all necessary styles and meta tags.
 *
 * @example
 * ```ts
 * const html = generateEmailHtml({
 *   header: generateHeader({
 *     icon: getSuccessIcon(),
 *     title: "Rezervacija potvrđena!",
 *     bookingReference: "RAB-ABC123"
 *   }),
 *   content: `
 *     ${generateCard("Detalji rezervacije", detailsHtml)}
 *     ${generateButton({text: "Pregledaj", url: "https://..."})}
 *   `,
 *   footer: {
 *     contactEmail: "info@example.com"
 *   }
 * });
 * ```
 */
export function generateEmailHtml(options: BaseEmailOptions): string {
  const {header, content, footer} = options;

  // Generate footer HTML
  const footerHtml = generateFooter(footer);

  // Combine all content sections
  const emailContent = `
    ${header}
    <div class="content">
      ${content}
    </div>
    ${footerHtml}
  `;

  // Wrap in email container
  const wrappedContent = wrapEmailContent(emailContent);

  // Wrap with base HTML structure (includes styles)
  const finalHtml = getBaseHtmlWrapper(`
    ${getComponentStyles()}
    ${wrappedContent}
  `);

  return finalHtml;
}

/**
 * Legacy function name for backward compatibility
 * @deprecated Use generateEmailHtml instead
 */
export function buildEmailTemplate(options: BaseEmailOptions): string {
  return generateEmailHtml(options);
}
