/**
 * Base Email Template - Inline Styles Version
 *
 * Core template structure used by all email types.
 * All styling is done via inline styles for Gmail compatibility.
 */

import {getBaseHtmlWrapper} from "../styles/base-styles";
import {wrapEmailContent, generateFooter, FooterOptions} from "../utils/template-helpers";

/**
 * Base email template options
 */
export interface BaseEmailOptions {
  /** Header HTML (generated by generateHeader) */
  header: string;

  /** Main content HTML (cards, alerts, buttons, etc.) */
  content: string;

  /** Footer options (optional) */
  footer?: FooterOptions;
}

/**
 * Generate complete email HTML
 *
 * Takes header, content, and footer options and returns a complete
 * HTML email with all necessary styles and meta tags.
 *
 * @example
 * ```ts
 * const html = generateEmailHtml({
 *   header: generateHeader({
 *     emoji: "✅",
 *     title: "Rezervacija potvrđena!",
 *     bookingReference: "RAB-ABC123"
 *   }),
 *   content: `
 *     ${generateCard("Detalji rezervacije", detailsHtml)}
 *     ${generateButton({text: "Pregledaj", url: "https://..."})}
 *   `,
 *   footer: {
 *     contactEmail: "info@example.com"
 *   }
 * });
 * ```
 */
export function generateEmailHtml(options: BaseEmailOptions): string {
  const {header, content, footer} = options;

  // Generate footer HTML
  const footerHtml = generateFooter(footer);

  // Combine all content sections with inline padding
  // Mobile-friendly padding: 16px horizontal, 20px bottom
  const emailContent = `
    ${header}
    <div class="content-wrapper" style="padding: 0 16px 20px 16px;">
      ${content}
    </div>
    ${footerHtml}
  `;

  // Wrap in email container (applies card background, border, shadow)
  const wrappedContent = wrapEmailContent(emailContent);

  // Wrap with base HTML structure (DOCTYPE, meta tags, minimal reset)
  const finalHtml = getBaseHtmlWrapper(wrappedContent);

  return finalHtml;
}

/**
 * Legacy function name for backward compatibility
 * @deprecated Use generateEmailHtml instead
 */
export function buildEmailTemplate(options: BaseEmailOptions): string {
  return generateEmailHtml(options);
}
