import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../../core/constants/breakpoints.dart';
import '../../../../core/theme/theme_extensions.dart';
import '../../../../core/utils/navigation_helpers.dart';
import '../../../../shared/models/booking_model.dart';
import '../../../../shared/providers/repository_providers.dart';
import '../../../auth/presentation/providers/auth_notifier.dart';
import '../../../auth/presentation/utils/form_validators.dart';
import '../../domain/models/booking_status.dart';
import '../../data/booking_notification_service.dart';
import '../providers/booking_flow_notifier.dart';
import '../utils/booking_error_parser.dart';

/// Booking review screen with guest details and price breakdown
class BookingReviewScreen extends ConsumerStatefulWidget {
  const BookingReviewScreen({super.key});

  @override
  ConsumerState<BookingReviewScreen> createState() =>
      _BookingReviewScreenState();
}

class _BookingReviewScreenState extends ConsumerState<BookingReviewScreen> {
  final _formKey = GlobalKey<FormState>();
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _specialRequestsController = TextEditingController();
  bool _acceptedTerms = false;

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _specialRequestsController.dispose();
    super.dispose();
  }

  Future<void> _proceedToPayment() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    // Check if terms are accepted
    if (!_acceptedTerms) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Morate prihvatiti uslove korištenja'),
          backgroundColor: context.warningColor,
        ),
      );
      return;
    }

    final bookingFlow = ref.read(bookingFlowNotifierProvider.notifier);
    final state = ref.read(bookingFlowNotifierProvider);
    final authState = ref.read(authNotifierProvider);

    // Check if user is authenticated
    if (authState.user == null) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('Morate biti prijavljeni za rezervaciju'),
            backgroundColor: context.errorColor,
          ),
        );
        context.goToLogin();
      }
      return;
    }

    // Update guest details
    bookingFlow.updateGuestDetails(
      firstName: _firstNameController.text.trim(),
      lastName: _lastNameController.text.trim(),
      email: _emailController.text.trim(),
      phone: _phoneController.text.trim(),
      specialRequests: _specialRequestsController.text.trim(),
    );

    try {
      bookingFlow.setLoading(true);

      // Create booking model with pending status
      final bookingModel = BookingModel(
        id: '', // Will be generated by database
        unitId: state.selectedUnit!.id,
        userId: authState.user!.id,
        checkIn: state.checkInDate!,
        checkOut: state.checkOutDate!,
        status: BookingStatus.pending,
        totalPrice: state.totalPrice,
        paidAmount: 0.0,
        guestCount: state.numberOfGuests,
        notes: _specialRequestsController.text.trim().isEmpty
            ? null
            : _specialRequestsController.text.trim(),
        createdAt: DateTime.now(),
      );

      // Create booking with pending_payment status
      final booking =
          await ref.read(bookingRepositoryProvider).createBooking(bookingModel);

      // Store booking ID
      bookingFlow.setBookingId(booking.id);

      // Send booking confirmation email (non-blocking)
      // This will call Supabase Edge Function to send email notification
      _sendConfirmationEmail(booking.id);

      bookingFlow.setLoading(false);

      // Navigate to payment screen
      if (mounted) {
        context.goToPayment(booking.id);
      }
    } catch (e) {
      bookingFlow.setLoading(false);
      bookingFlow.setError(e.toString());

      if (mounted) {
        _showBookingErrorDialog(e.toString());
      }
    }
  }

  /// Send confirmation email asynchronously (non-blocking)
  /// This will call the Supabase Edge Function to send the email
  /// Email sending failures won't block the booking flow
  void _sendConfirmationEmail(String bookingId) {
    // Run email sending in the background (fire and forget)
    ref.read(bookingNotificationServiceProvider).sendBookingConfirmation(bookingId).then((success) {
      if (success) {
        debugPrint('✅ Confirmation email sent successfully for booking: $bookingId');
      } else {
        debugPrint('⚠️ Failed to send confirmation email for booking: $bookingId');
        // Note: We don't show error to user as email is not critical for booking flow
        // Admin can retry sending email from dashboard if needed
      }
    }).catchError((error) {
      debugPrint('❌ Error sending confirmation email: $error');
    });
  }

  /// Show booking error dialog with retry option
  void _showBookingErrorDialog(String errorMessage) {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => AlertDialog(
        title: Row(
          children: [
            Icon(Icons.error_outline, color: context.errorColor, size: 28),
            const SizedBox(width: 12),
            const Text('Greška pri rezervaciji'),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(BookingErrorParser.getUserFriendlyMessage(errorMessage)),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: context.surfaceColor,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.info_outline, size: 20, color: context.primaryColor),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'Molimo provjerite vašu internet vezu i pokušajte ponovo.',
                      style: TextStyle(
                        fontSize: 12,
                        color: context.textColorSecondary,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
              context.goBack();
            },
            child: const Text('Odustani'),
          ),
          FilledButton.icon(
            onPressed: () {
              Navigator.of(context).pop();
              _proceedToPayment();
            },
            icon: const Icon(Icons.refresh),
            label: const Text('Pokušaj ponovo'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final bookingFlow = ref.watch(bookingFlowNotifierProvider);
    final isMobile = Breakpoints.isMobile(context);

    if (bookingFlow.property == null || bookingFlow.selectedUnit == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Greška')),
        body: const Center(
          child: Text('Podaci o rezervaciji nisu pronađeni'),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Pregled rezervacije'),
        elevation: 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.all(isMobile ? 16 : 24),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Booking summary card
                _buildBookingSummaryCard(bookingFlow, isMobile),
                const SizedBox(height: 24),

                // Guest details section
                _buildGuestDetailsSection(isMobile),
                const SizedBox(height: 24),

                // Price breakdown card
                _buildPriceBreakdownCard(bookingFlow, isMobile),
                const SizedBox(height: 24),

                // Terms & Conditions
                _buildTermsAndConditions(),
                const SizedBox(height: 32),

                // Proceed to payment button
                FilledButton(
                  onPressed: bookingFlow.isLoading ? null : _proceedToPayment,
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: bookingFlow.isLoading
                      ? SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: context.surfaceColor,
                          ),
                        )
                      : const Text('Nastavi na plaćanje'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildBookingSummaryCard(
      BookingFlowState bookingFlow, bool isMobile) {
    final dateFormat = DateFormat('dd.MM.yyyy');
    final nights = bookingFlow.checkOutDate!.difference(bookingFlow.checkInDate!).inDays;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              bookingFlow.property!.name,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const SizedBox(height: 8),
            Text(
              bookingFlow.selectedUnit!.name,
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const Divider(height: 24),
            _buildInfoRow(
              Icons.calendar_today,
              'Dolazak',
              dateFormat.format(bookingFlow.checkInDate!),
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.calendar_today,
              'Odlazak',
              dateFormat.format(bookingFlow.checkOutDate!),
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.nightlight_round,
              'Broj noći',
              '$nights ${nights == 1 ? 'noć' : nights < 5 ? 'noći' : 'noći'}',
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.people,
              'Gosti',
              '${bookingFlow.numberOfGuests} ${bookingFlow.numberOfGuests == 1 ? 'gost' : 'gostiju'}',
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGuestDetailsSection(bool isMobile) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Podaci o gostu',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
        ),
        const SizedBox(height: 16),
        // Responsive row/column for name fields
        // Column on mobile (< 600px), Row on tablet/desktop
        LayoutBuilder(
          builder: (context, constraints) {
            final isMobileLayout = constraints.maxWidth < 600;

            if (isMobileLayout) {
              // Stack vertically on mobile
              return Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  TextFormField(
                    controller: _firstNameController,
                    decoration: const InputDecoration(
                      labelText: 'Ime',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.person_outline),
                    ),
                    validator: (value) =>
                        FormValidators.validateName(value, 'Ime'),
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _lastNameController,
                    decoration: const InputDecoration(
                      labelText: 'Prezime',
                      border: OutlineInputBorder(),
                    ),
                    validator: (value) =>
                        FormValidators.validateName(value, 'Prezime'),
                  ),
                ],
              );
            } else {
              // Side by side on tablet/desktop
              return Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _firstNameController,
                      decoration: const InputDecoration(
                        labelText: 'Ime',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.person_outline),
                      ),
                      validator: (value) =>
                          FormValidators.validateName(value, 'Ime'),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _lastNameController,
                      decoration: const InputDecoration(
                        labelText: 'Prezime',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) =>
                          FormValidators.validateName(value, 'Prezime'),
                    ),
                  ),
                ],
              );
            }
          },
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _emailController,
          keyboardType: TextInputType.emailAddress,
          decoration: const InputDecoration(
            labelText: 'Email',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.email_outlined),
          ),
          validator: FormValidators.validateEmail,
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _phoneController,
          keyboardType: TextInputType.phone,
          decoration: const InputDecoration(
            labelText: 'Telefon',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.phone_outlined),
          ),
          validator: (value) =>
              FormValidators.validateRequired(value, 'Telefon'),
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _specialRequestsController,
          maxLines: 3,
          decoration: const InputDecoration(
            labelText: 'Posebni zahtjevi (opcionalno)',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.message_outlined),
          ),
        ),
      ],
    );
  }

  Widget _buildPriceBreakdownCard(
      BookingFlowState bookingFlow, bool isMobile) {
    final nights = bookingFlow.checkOutDate!.difference(bookingFlow.checkInDate!).inDays;

    return Card(
      color: Theme.of(context).colorScheme.primaryContainer,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Detalji cijene',
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const Divider(height: 24),
            _buildPriceRow(
              '€${bookingFlow.selectedUnit!.pricePerNight.toStringAsFixed(2)} × $nights ${nights == 1 ? 'noć' : 'noći'}',
              '€${bookingFlow.basePrice.toStringAsFixed(2)}',
            ),
            const SizedBox(height: 8),
            _buildPriceRow(
              'Naknada za uslugu (10%)',
              '€${bookingFlow.serviceFee.toStringAsFixed(2)}',
            ),
            const SizedBox(height: 8),
            _buildPriceRow(
              'Naknada za čišćenje',
              '€${bookingFlow.cleaningFee.toStringAsFixed(2)}',
            ),
            const Divider(height: 24),
            _buildPriceRow(
              'Ukupno',
              '€${bookingFlow.totalPrice.toStringAsFixed(2)}',
              isTotal: true,
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.secondary,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Za platiti sada (20% avansa)',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                          color: context.surfaceColor,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                  Text(
                    '€${bookingFlow.advancePaymentAmount.toStringAsFixed(2)}',
                    style: Theme.of(context).textTheme.titleLarge?.copyWith(
                          color: context.surfaceColor,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildInfoRow(IconData icon, String label, String value) {
    return Row(
      children: [
        Icon(icon, size: 20, color: context.textColorSecondary),
        const SizedBox(width: 8),
        Text(
          '$label: ',
          style: TextStyle(color: context.textColorSecondary),
        ),
        Text(
          value,
          style: const TextStyle(fontWeight: FontWeight.w600),
        ),
      ],
    );
  }

  Widget _buildPriceRow(String label, String value, {bool isTotal = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: isTotal
              ? Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  )
              : null,
        ),
        Text(
          value,
          style: isTotal
              ? Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  )
              : const TextStyle(fontWeight: FontWeight.w600),
        ),
      ],
    );
  }

  Widget _buildTermsAndConditions() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        border: Border.all(color: context.borderColor),
        borderRadius: BorderRadius.circular(8),
        color: context.surfaceColor,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Checkbox(
                value: _acceptedTerms,
                onChanged: (value) {
                  setState(() {
                    _acceptedTerms = value ?? false;
                  });
                },
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.only(top: 12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Prihvaćam uslove korištenja i politiku otkazivanja',
                        style: Theme.of(context).textTheme.bodyMedium,
                      ),
                      const SizedBox(height: 8),
                      InkWell(
                        onTap: _showCancellationPolicy,
                        child: Text(
                          'Pogledaj politiku otkazivanja',
                          style:
                              Theme.of(context).textTheme.bodySmall?.copyWith(
                                    color: Theme.of(context).colorScheme.primary,
                                    decoration: TextDecoration.underline,
                                  ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  void _showCancellationPolicy() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Politika otkazivanja'),
        content: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(
                'Besplatno otkazivanje',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
              ),
              const SizedBox(height: 8),
              const Text(
                '• Potpuni povrat novca ako otkažete najmanje 7 dana prije dolaska',
              ),
              const SizedBox(height: 16),
              Text(
                'Djelomični povrat',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
              ),
              const SizedBox(height: 8),
              const Text(
                '• 50% povrat novca ako otkažete 3-7 dana prije dolaska',
              ),
              const SizedBox(height: 16),
              Text(
                'Bez povrata',
                style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.bold,
                    ),
              ),
              const SizedBox(height: 8),
              const Text(
                '• Nema povrata novca ako otkažete manje od 3 dana prije dolaska',
              ),
              const SizedBox(height: 16),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: context.surfaceColor,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Icon(Icons.info_outline,
                        size: 20, color: context.primaryColor),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Plaćeni avans od 20% služi kao garancija rezervacije. Preostali iznos se plaća prilikom prijave.',
                        style: TextStyle(
                          fontSize: 12,
                          color: context.textColorSecondary,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Zatvori'),
          ),
        ],
      ),
    );
  }
}
