import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../../core/constants/enums.dart';
import '../../../../core/utils/navigation_helpers.dart';
import '../../../../shared/models/booking_model.dart';
import '../../../../shared/providers/repository_providers.dart';
import '../../../auth/presentation/providers/auth_notifier.dart';
import '../../../auth/presentation/utils/form_validators.dart';
import '../providers/booking_flow_notifier.dart';

/// Booking review screen with guest details and price breakdown
class BookingReviewScreen extends ConsumerStatefulWidget {
  const BookingReviewScreen({super.key});

  @override
  ConsumerState<BookingReviewScreen> createState() =>
      _BookingReviewScreenState();
}

class _BookingReviewScreenState extends ConsumerState<BookingReviewScreen> {
  final _formKey = GlobalKey<FormState>();
  final _firstNameController = TextEditingController();
  final _lastNameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _specialRequestsController = TextEditingController();

  @override
  void dispose() {
    _firstNameController.dispose();
    _lastNameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _specialRequestsController.dispose();
    super.dispose();
  }

  Future<void> _proceedToPayment() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    final bookingFlow = ref.read(bookingFlowNotifierProvider.notifier);
    final state = ref.read(bookingFlowNotifierProvider);
    final authState = ref.read(authNotifierProvider);

    // Check if user is authenticated
    if (authState.user == null) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Morate biti prijavljeni za rezervaciju'),
            backgroundColor: Colors.red,
          ),
        );
        context.goToLogin();
      }
      return;
    }

    // Update guest details
    bookingFlow.updateGuestDetails(
      firstName: _firstNameController.text.trim(),
      lastName: _lastNameController.text.trim(),
      email: _emailController.text.trim(),
      phone: _phoneController.text.trim(),
      specialRequests: _specialRequestsController.text.trim(),
    );

    try {
      bookingFlow.setLoading(true);

      // Create booking model with pending_payment status
      final bookingModel = BookingModel(
        id: '', // Will be generated by database
        unitId: state.selectedUnit!.id,
        guestId: authState.user!.id,
        checkIn: state.checkInDate!,
        checkOut: state.checkOutDate!,
        status: BookingStatus.pendingPayment,
        totalPrice: state.totalPrice,
        paidAmount: 0.0,
        guestCount: state.numberOfGuests,
        notes: _specialRequestsController.text.trim().isEmpty
            ? null
            : _specialRequestsController.text.trim(),
        createdAt: DateTime.now(),
      );

      // Create booking with pending_payment status
      final booking =
          await ref.read(bookingRepositoryProvider).createBooking(bookingModel);

      // Store booking ID
      bookingFlow.setBookingId(booking.id);
      bookingFlow.setLoading(false);

      // Navigate to payment screen
      if (mounted) {
        context.goToPayment(booking.id);
      }
    } catch (e) {
      bookingFlow.setLoading(false);
      bookingFlow.setError(e.toString());

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Greška: ${e.toString()}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final bookingFlow = ref.watch(bookingFlowNotifierProvider);
    final isMobile = MediaQuery.of(context).size.width < 768;

    if (bookingFlow.property == null || bookingFlow.selectedUnit == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Greška')),
        body: const Center(
          child: Text('Podaci o rezervaciji nisu pronađeni'),
        ),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: const Text('Pregled rezervacije'),
        elevation: 0,
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: EdgeInsets.all(isMobile ? 16 : 24),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                // Booking summary card
                _buildBookingSummaryCard(bookingFlow, isMobile),
                const SizedBox(height: 24),

                // Guest details section
                _buildGuestDetailsSection(isMobile),
                const SizedBox(height: 24),

                // Price breakdown card
                _buildPriceBreakdownCard(bookingFlow, isMobile),
                const SizedBox(height: 32),

                // Proceed to payment button
                FilledButton(
                  onPressed: bookingFlow.isLoading ? null : _proceedToPayment,
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: bookingFlow.isLoading
                      ? const SizedBox(
                          height: 20,
                          width: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.white,
                          ),
                        )
                      : const Text('Nastavi na plaćanje'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildBookingSummaryCard(
      BookingFlowState bookingFlow, bool isMobile) {
    final dateFormat = DateFormat('dd.MM.yyyy');
    final nights = bookingFlow.nights;

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              bookingFlow.property!.name,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const SizedBox(height: 8),
            Text(
              bookingFlow.selectedUnit!.name,
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const Divider(height: 24),
            _buildInfoRow(
              Icons.calendar_today,
              'Dolazak',
              dateFormat.format(bookingFlow.checkInDate!),
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.calendar_today,
              'Odlazak',
              dateFormat.format(bookingFlow.checkOutDate!),
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.nightlight_round,
              'Broj noći',
              '$nights ${nights == 1 ? 'noć' : nights < 5 ? 'noći' : 'noći'}',
            ),
            const SizedBox(height: 8),
            _buildInfoRow(
              Icons.people,
              'Gosti',
              '${bookingFlow.numberOfGuests} ${bookingFlow.numberOfGuests == 1 ? 'gost' : 'gostiju'}',
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGuestDetailsSection(bool isMobile) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Podaci o gostu',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            Expanded(
              child: TextFormField(
                controller: _firstNameController,
                decoration: const InputDecoration(
                  labelText: 'Ime',
                  border: OutlineInputBorder(),
                  prefixIcon: Icon(Icons.person_outline),
                ),
                validator: (value) =>
                    FormValidators.validateName(value, 'Ime'),
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: TextFormField(
                controller: _lastNameController,
                decoration: const InputDecoration(
                  labelText: 'Prezime',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    FormValidators.validateName(value, 'Prezime'),
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _emailController,
          keyboardType: TextInputType.emailAddress,
          decoration: const InputDecoration(
            labelText: 'Email',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.email_outlined),
          ),
          validator: FormValidators.validateEmail,
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _phoneController,
          keyboardType: TextInputType.phone,
          decoration: const InputDecoration(
            labelText: 'Telefon',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.phone_outlined),
          ),
          validator: (value) =>
              FormValidators.validateRequired(value, 'Telefon'),
        ),
        const SizedBox(height: 16),
        TextFormField(
          controller: _specialRequestsController,
          maxLines: 3,
          decoration: const InputDecoration(
            labelText: 'Posebni zahtjevi (opcionalno)',
            border: OutlineInputBorder(),
            prefixIcon: Icon(Icons.message_outlined),
          ),
        ),
      ],
    );
  }

  Widget _buildPriceBreakdownCard(
      BookingFlowState bookingFlow, bool isMobile) {
    final nights = bookingFlow.nights;

    return Card(
      color: Theme.of(context).colorScheme.primaryContainer,
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Detalji cijene',
              style: Theme.of(context).textTheme.titleLarge?.copyWith(
                    fontWeight: FontWeight.bold,
                  ),
            ),
            const Divider(height: 24),
            _buildPriceRow(
              '€${bookingFlow.selectedUnit!.pricePerNight.toStringAsFixed(2)} × $nights ${nights == 1 ? 'noć' : 'noći'}',
              '€${bookingFlow.basePrice.toStringAsFixed(2)}',
            ),
            const SizedBox(height: 8),
            _buildPriceRow(
              'Naknada za uslugu (10%)',
              '€${bookingFlow.serviceFee.toStringAsFixed(2)}',
            ),
            const SizedBox(height: 8),
            _buildPriceRow(
              'Naknada za čišćenje',
              '€${bookingFlow.cleaningFee.toStringAsFixed(2)}',
            ),
            const Divider(height: 24),
            _buildPriceRow(
              'Ukupno',
              '€${bookingFlow.totalPrice.toStringAsFixed(2)}',
              isTotal: true,
            ),
            const SizedBox(height: 16),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.secondary,
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'Za platiti sada (20% avansa)',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                  Text(
                    '€${bookingFlow.advanceAmount.toStringAsFixed(2)}',
                    style: Theme.of(context).textTheme.titleLarge?.copyWith(
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildInfoRow(IconData icon, String label, String value) {
    return Row(
      children: [
        Icon(icon, size: 20, color: Colors.grey[600]),
        const SizedBox(width: 8),
        Text(
          '$label: ',
          style: TextStyle(color: Colors.grey[600]),
        ),
        Text(
          value,
          style: const TextStyle(fontWeight: FontWeight.w600),
        ),
      ],
    );
  }

  Widget _buildPriceRow(String label, String value, {bool isTotal = false}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: isTotal
              ? Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  )
              : null,
        ),
        Text(
          value,
          style: isTotal
              ? Theme.of(context).textTheme.titleMedium?.copyWith(
                    fontWeight: FontWeight.bold,
                  )
              : const TextStyle(fontWeight: FontWeight.w600),
        ),
      ],
    );
  }
}
