// Firebase options for STAGING environment (bookbed-staging)
// Generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'StagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEayEl_0_Ne3Xwy8bEaEqI0Mybe4LTGrU',
    appId: '1:584902480248:web:767f9d3bc1837eea94f88d',
    messagingSenderId: '584902480248',
    projectId: 'bookbed-staging',
    authDomain: 'bookbed-staging.firebaseapp.com',
    storageBucket: 'bookbed-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALJXlleVlYF4xtBbumGiOO8nObxzn5r2M',
    appId: '1:584902480248:android:a53609e3e6dc177d94f88d',
    messagingSenderId: '584902480248',
    projectId: 'bookbed-staging',
    storageBucket: 'bookbed-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnnBk6C9SJn0oXFKaIYKh9P5EgyBUtYxI',
    appId: '1:584902480248:ios:c7e20d5f21438baf94f88d',
    messagingSenderId: '584902480248',
    projectId: 'bookbed-staging',
    storageBucket: 'bookbed-staging.firebasestorage.app',
    iosBundleId: 'io.bookbed.app',
  );
}
