// Firebase options for DEVELOPMENT environment (bookbed-dev)
// Generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc6vDPLBTN3ePkY39Pw9Jrheh30OhLWEM',
    appId: '1:733027606474:web:cdac74e20c8fb05aebf933',
    messagingSenderId: '733027606474',
    projectId: 'bookbed-dev',
    authDomain: 'bookbed-dev.firebaseapp.com',
    storageBucket: 'bookbed-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCokYMO3Q0Q8cM5f_y4Ne8C3GaP7cwR-bE',
    appId: '1:733027606474:android:90cb9dbd5e2e4adbebf933',
    messagingSenderId: '733027606474',
    projectId: 'bookbed-dev',
    storageBucket: 'bookbed-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA857meSxpfUFDvF7ZorkTrKrOQZi152go',
    appId: '1:733027606474:ios:600363248e5e0e5aebf933',
    messagingSenderId: '733027606474',
    projectId: 'bookbed-dev',
    storageBucket: 'bookbed-dev.firebasestorage.app',
    iosBundleId: 'io.bookbed.app',
  );
}
