// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2J8MaHvIU1sw4ItO3tzsn5LC9pDvgD5s',
    appId: '1:592597958982:web:7703de3f5a2ab47d',
    messagingSenderId: '592597958982',
    projectId: 'rab-booking-248fc',
    authDomain: 'rab-booking-248fc.firebaseapp.com',
    storageBucket: 'rab-booking-248fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7edb0FWFzr23pm6xmjmrlehdL1Ysxvwc',
    appId: '1:592597958982:android:28730515db1ea267d3e547',
    messagingSenderId: '592597958982',
    projectId: 'rab-booking-248fc',
    storageBucket: 'rab-booking-248fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOFQ2jykLZlTtE6whuGDb-09r8HyAHs90',
    appId: '1:592597958982:ios:7703de3f5a2ab47d',
    messagingSenderId: '592597958982',
    projectId: 'rab-booking-248fc',
    storageBucket: 'rab-booking-248fc.firebasestorage.app',
    iosBundleId: 'com.example.novaAplikacija',
  );
}
